## Google COVID-19 Community Mobility Report data

In [7]:
import pandas as pd
import numpy as np

In [2]:
google = pd.read_csv("2020_GB_Region_Mobility_Report.csv")
google

,country_region_code,country_region,sub_region_1,sub_region_2,metro_area,iso_3166_2_code,census_fips_code,place_id,date,retail_and_recreation_percent_change_from_baseline,grocery_and_pharmacy_percent_change_from_baseline,parks_percent_change_from_baseline,transit_stations_percent_change_from_baseline,workplaces_percent_change_from_baseline,residential_percent_change_from_baseline
0,GB,United Kingdom,NaN,NaN,NaN,NaN,NaN,ChIJqZHHQhE7WgIReiWIMkOg-MQ,2020-02-15,-12.0,-7.0,-35.0,-12.0,-4.0,2.0
1,GB,United Kingdom,NaN,NaN,NaN,NaN,NaN,ChIJqZHHQhE7WgIReiWIMkOg-MQ,2020-02-16,-7.0,-6.0,-28.0,-7.0,-3.0,1.0
2,GB,United Kingdom,NaN,NaN,NaN,NaN,NaN,ChIJqZHHQhE7WgIReiWIMkOg-MQ,2020-02-17,10.0,1.0,24.0,-2.0,-14.0,2.0
3,GB,United Kingdom,NaN,NaN,NaN,NaN,NaN,ChIJqZHHQhE7WgIReiWIMkOg-MQ,2020-02-18,7.0,-1.0,20.0,-3.0,-14.0,2.0
4,GB,United Kingdom,NaN,NaN,NaN,NaN,NaN,ChIJqZHHQhE7WgIReiWIMkOg-MQ,2020-02-19,6.0,-2.0,8.0,-4.0,-14.0,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
133377,GB,United Kingdom,York,NaN,NaN,GB-YOR,NaN,ChIJh-IigLwxeUgRAKFv7Z75DAM,2020-12-27,-51.0,-26.0,-32.0,-38.0,-20.0,9.0
133378,GB,United Kingdom,York,NaN,NaN,GB-YOR,NaN,ChIJh-IigLwxeUgRAKFv7Z75DAM,2020-12-28,-25.0,-16.0,21.0,-35.0,-73.0,23.0
133379,GB,United Kingdom,York,NaN,NaN,GB-YOR,NaN,ChIJh-IigLwxeUgRAKFv7Z75DAM,2020-12-29,-22.0,-6.0,14.0,-37.0,-64.0,21.0
133380,GB,United Kingdom,York,NaN,NaN,GB-YOR,NaN,ChIJh-IigLwxeUgRAKFv7Z75DAM,2020-12-30,-22.0,-1.0,7.0,-37.0,-62.0,20.0
133381,GB,United Kingdom,York,NaN,NaN,GB-YOR,NaN,ChIJh-IigLwxeUgRAKFv7Z75DAM,2020-12-31,-46.0,3.0,7.0,-57.0,-67.0,23.0

In [6]:
london = google[google.sub_region_1=='Greater London']
london

,country_region_code,country_region,sub_region_1,sub_region_2,metro_area,iso_3166_2_code,census_fips_code,place_id,date,retail_and_recreation_percent_change_from_baseline,grocery_and_pharmacy_percent_change_from_baseline,parks_percent_change_from_baseline,transit_stations_percent_change_from_baseline,workplaces_percent_change_from_baseline,residential_percent_change_from_baseline
36253,GB,United Kingdom,Greater London,NaN,NaN,NaN,NaN,ChIJb-IaoQug2EcRi-m4hONz8S8,2020-02-15,-11.0,-8.0,-34.0,-10.0,-3.0,2.0
36254,GB,United Kingdom,Greater London,NaN,NaN,NaN,NaN,ChIJb-IaoQug2EcRi-m4hONz8S8,2020-02-16,-9.0,-11.0,-41.0,-9.0,-4.0,1.0
36255,GB,United Kingdom,Greater London,NaN,NaN,NaN,NaN,ChIJb-IaoQug2EcRi-m4hONz8S8,2020-02-17,11.0,4.0,28.0,-3.0,-13.0,2.0
36256,GB,United Kingdom,Greater London,NaN,NaN,NaN,NaN,ChIJb-IaoQug2EcRi-m4hONz8S8,2020-02-18,4.0,-2.0,11.0,-4.0,-13.0,2.0
36257,GB,United Kingdom,Greater London,NaN,NaN,NaN,NaN,ChIJb-IaoQug2EcRi-m4hONz8S8,2020-02-19,3.0,-3.0,3.0,-5.0,-13.0,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
47162,GB,United Kingdom,Greater London,Royal Borough of Kingston upon Thames,NaN,GB-KTT,NaN,ChIJ0ycUEikKdkgR6r_eW1XvlAQ,2020-12-27,-72.0,-31.0,40.0,-58.0,-42.0,12.0
47163,GB,United Kingdom,Greater London,Royal Borough of Kingston upon Thames,NaN,GB-KTT,NaN,ChIJ0ycUEikKdkgR6r_eW1XvlAQ,2020-12-28,-67.0,-32.0,NaN,-76.0,-84.0,32.0
47164,GB,United Kingdom,Greater London,Royal Borough of Kingston upon Thames,NaN,GB-KTT,NaN,ChIJ0ycUEikKdkgR6r_eW1XvlAQ,2020-12-29,-62.0,-19.0,NaN,-69.0,-77.0,29.0
47165,GB,United Kingdom,Greater London,Royal Borough of Kingston upon Thames,NaN,GB-KTT,NaN,ChIJ0ycUEikKdkgR6r_eW1XvlAQ,2020-12-30,-61.0,-10.0,NaN,-68.0,-74.0,30.0
47166,GB,United Kingdom,Greater London,Royal Borough of Kingston upon Thames,NaN,GB-KTT,NaN,ChIJ0ycUEikKdkgR6r_eW1XvlAQ,2020-12-31,-63.0,-3.0,NaN,-70.0,-77.0,30.0

In [26]:
london_all = london[london.sub_region_2.astype('str')=='nan']
london_all

,country_region_code,country_region,sub_region_1,sub_region_2,metro_area,iso_3166_2_code,census_fips_code,place_id,date,retail_and_recreation_percent_change_from_baseline,grocery_and_pharmacy_percent_change_from_baseline,parks_percent_change_from_baseline,transit_stations_percent_change_from_baseline,workplaces_percent_change_from_baseline,residential_percent_change_from_baseline
36253,GB,United Kingdom,Greater London,NaN,NaN,NaN,NaN,ChIJb-IaoQug2EcRi-m4hONz8S8,2020-02-15,-11.0,-8.0,-34.0,-10.0,-3.0,2.0
36254,GB,United Kingdom,Greater London,NaN,NaN,NaN,NaN,ChIJb-IaoQug2EcRi-m4hONz8S8,2020-02-16,-9.0,-11.0,-41.0,-9.0,-4.0,1.0
36255,GB,United Kingdom,Greater London,NaN,NaN,NaN,NaN,ChIJb-IaoQug2EcRi-m4hONz8S8,2020-02-17,11.0,4.0,28.0,-3.0,-13.0,2.0
36256,GB,United Kingdom,Greater London,NaN,NaN,NaN,NaN,ChIJb-IaoQug2EcRi-m4hONz8S8,2020-02-18,4.0,-2.0,11.0,-4.0,-13.0,2.0
36257,GB,United Kingdom,Greater London,NaN,NaN,NaN,NaN,ChIJb-IaoQug2EcRi-m4hONz8S8,2020-02-19,3.0,-3.0,3.0,-5.0,-13.0,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
36569,GB,United Kingdom,Greater London,NaN,NaN,NaN,NaN,ChIJb-IaoQug2EcRi-m4hONz8S8,2020-12-27,-71.0,-32.0,-8.0,-68.0,-35.0,12.0
36570,GB,United Kingdom,Greater London,NaN,NaN,NaN,NaN,ChIJb-IaoQug2EcRi-m4hONz8S8,2020-12-28,-68.0,-31.0,-4.0,-78.0,-80.0,31.0
36571,GB,United Kingdom,Greater London,NaN,NaN,NaN,NaN,ChIJb-IaoQug2EcRi-m4hONz8S8,2020-12-29,-65.0,-21.0,-11.0,-73.0,-72.0,28.0
36572,GB,United Kingdom,Greater London,NaN,NaN,NaN,NaN,ChIJb-IaoQug2EcRi-m4hONz8S8,2020-12-30,-64.0,-14.0,2.0,-73.0,-71.0,28.0
36573,GB,United Kingdom,Greater London,NaN,NaN,NaN,NaN,ChIJb-IaoQug2EcRi-m4hONz8S8,2020-12-31,-65.0,-7.0,-12.0,-74.0,-73.0,29.0

In [40]:
london_all.drop(['country_region_code', 'country_region', 'sub_region_1', 'sub_region_2',
                 'metro_area', 'iso_3166_2_code', 'census_fips_code', 'place_id'], axis=1)
london_all.reset_index(drop=True, inplace=True)

In [44]:
london_all.to_csv('../datasets/google_greater_london.csv', index=False)

In [47]:
london_all.set_index('date', inplace=True)
london_all

,retail_and_recreation_percent_change_from_baseline,grocery_and_pharmacy_percent_change_from_baseline,parks_percent_change_from_baseline,transit_stations_percent_change_from_baseline,workplaces_percent_change_from_baseline,residential_percent_change_from_baseline
date,,,,,,
2020-02-15,-11.0,-8.0,-34.0,-10.0,-3.0,2.0
2020-02-16,-9.0,-11.0,-41.0,-9.0,-4.0,1.0
2020-02-17,11.0,4.0,28.0,-3.0,-13.0,2.0
2020-02-18,4.0,-2.0,11.0,-4.0,-13.0,2.0
2020-02-19,3.0,-3.0,3.0,-5.0,-13.0,3.0
...,...,...,...,...,...,...
2020-12-27,-71.0,-32.0,-8.0,-68.0,-35.0,12.0
2020-12-28,-68.0,-31.0,-4.0,-78.0,-80.0,31.0
2020-12-29,-65.0,-21.0,-11.0,-73.0,-72.0,28.0
2020-12-30,-64.0,-14.0,2.0,-73.0,-71.0,28.0
2020-12-31,-65.0,-7.0,-12.0,-74.0,-73.0,29.0

In [49]:
# First lockdown
london_all.loc['2020-03-23':'2020-05-13'].mean()

retail_and_recreation_percent_change_from_baseline   -79.653846
grocery_and_pharmacy_percent_change_from_baseline    -33.653846
parks_percent_change_from_baseline                   -17.326923
transit_stations_percent_change_from_baseline        -76.403846
workplaces_percent_change_from_baseline              -70.365385
residential_percent_change_from_baseline              29.461538
dtype: float64

In [50]:
london_all.loc['2020-05-14':'2020-08-13'].mean()

retail_and_recreation_percent_change_from_baseline   -57.489130
grocery_and_pharmacy_percent_change_from_baseline    -19.119565
parks_percent_change_from_baseline                    40.934783
transit_stations_percent_change_from_baseline        -59.989130
workplaces_percent_change_from_baseline              -50.750000
residential_percent_change_from_baseline              18.728261
dtype: float64

## Comparing different London boroughs

In [58]:
london.drop(['country_region_code', 'country_region', 'sub_region_1',
             'metro_area', 'iso_3166_2_code', 'census_fips_code', 'place_id'], axis=1)
london

,sub_region_2,date,retail_and_recreation_percent_change_from_baseline,grocery_and_pharmacy_percent_change_from_baseline,parks_percent_change_from_baseline,transit_stations_percent_change_from_baseline,workplaces_percent_change_from_baseline,residential_percent_change_from_baseline
36253,NaN,2020-02-15,-11.0,-8.0,-34.0,-10.0,-3.0,2.0
36254,NaN,2020-02-16,-9.0,-11.0,-41.0,-9.0,-4.0,1.0
36255,NaN,2020-02-17,11.0,4.0,28.0,-3.0,-13.0,2.0
36256,NaN,2020-02-18,4.0,-2.0,11.0,-4.0,-13.0,2.0
36257,NaN,2020-02-19,3.0,-3.0,3.0,-5.0,-13.0,3.0
...,...,...,...,...,...,...,...,...
47162,Royal Borough of Kingston upon Thames,2020-12-27,-72.0,-31.0,40.0,-58.0,-42.0,12.0
47163,Royal Borough of Kingston upon Thames,2020-12-28,-67.0,-32.0,NaN,-76.0,-84.0,32.0
47164,Royal Borough of Kingston upon Thames,2020-12-29,-62.0,-19.0,NaN,-69.0,-77.0,29.0
47165,Royal Borough of Kingston upon Thames,2020-12-30,-61.0,-10.0,NaN,-68.0,-74.0,30.0
47166,Royal Borough of Kingston upon Thames,2020-12-31,-63.0,-3.0,NaN,-70.0,-77.0,30.0

In [77]:
## Looking at difference between boroughs
boroughs = london.groupby('sub_region_2').mean()

In [89]:
# Removing "Borough of" from the start of every Borough name
borough_names = []
for borough in boroughs.index:
    i = borough.find('of')
    if i>0:
        borough_names.append(borough[i+3:])
    else:
        borough_names.append(borough)
borough_names[0] = 'City of London'
borough_names

['City of London',
 'Westminster',
 'Barking and Dagenham',
 'Barnet',
 'Bexley',
 'Brent',
 'Bromley',
 'Camden',
 'Croydon',
 'Ealing',
 'Enfield',
 'Hackney',
 'Hammersmith and Fulham',
 'Haringey',
 'Harrow',
 'Havering',
 'Hillingdon',
 'Hounslow',
 'Islington',
 'Lambeth',
 'Lewisham',
 'Merton',
 'Newham',
 'Redbridge',
 'Richmond upon Thames',
 'Southwark',
 'Sutton',
 'Tower Hamlets',
 'Waltham Forest',
 'Wandsworth',
 'Greenwich',
 'Kensington and Chelsea',
 'Kingston upon Thames']

In [91]:
boroughs.index=borough_names
boroughs.to_csv('../datasets/google_boroughs.csv')