In [7]:
import pandas as pd
import numpy as np

In [2]:
google = pd.read_csv("2020_GB_Region_Mobility_Report.csv")
google

,country_region_code,country_region,sub_region_1,sub_region_2,metro_area,iso_3166_2_code,census_fips_code,place_id,date,retail_and_recreation_percent_change_from_baseline,grocery_and_pharmacy_percent_change_from_baseline,parks_percent_change_from_baseline,transit_stations_percent_change_from_baseline,workplaces_percent_change_from_baseline,residential_percent_change_from_baseline
0,GB,United Kingdom,NaN,NaN,NaN,NaN,NaN,ChIJqZHHQhE7WgIReiWIMkOg-MQ,2020-02-15,-12.0,-7.0,-35.0,-12.0,-4.0,2.0
1,GB,United Kingdom,NaN,NaN,NaN,NaN,NaN,ChIJqZHHQhE7WgIReiWIMkOg-MQ,2020-02-16,-7.0,-6.0,-28.0,-7.0,-3.0,1.0
2,GB,United Kingdom,NaN,NaN,NaN,NaN,NaN,ChIJqZHHQhE7WgIReiWIMkOg-MQ,2020-02-17,10.0,1.0,24.0,-2.0,-14.0,2.0
3,GB,United Kingdom,NaN,NaN,NaN,NaN,NaN,ChIJqZHHQhE7WgIReiWIMkOg-MQ,2020-02-18,7.0,-1.0,20.0,-3.0,-14.0,2.0
4,GB,United Kingdom,NaN,NaN,NaN,NaN,NaN,ChIJqZHHQhE7WgIReiWIMkOg-MQ,2020-02-19,6.0,-2.0,8.0,-4.0,-14.0,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
133377,GB,United Kingdom,York,NaN,NaN,GB-YOR,NaN,ChIJh-IigLwxeUgRAKFv7Z75DAM,2020-12-27,-51.0,-26.0,-32.0,-38.0,-20.0,9.0
133378,GB,United Kingdom,York,NaN,NaN,GB-YOR,NaN,ChIJh-IigLwxeUgRAKFv7Z75DAM,2020-12-28,-25.0,-16.0,21.0,-35.0,-73.0,23.0
133379,GB,United Kingdom,York,NaN,NaN,GB-YOR,NaN,ChIJh-IigLwxeUgRAKFv7Z75DAM,2020-12-29,-22.0,-6.0,14.0,-37.0,-64.0,21.0
133380,GB,United Kingdom,York,NaN,NaN,GB-YOR,NaN,ChIJh-IigLwxeUgRAKFv7Z75DAM,2020-12-30,-22.0,-1.0,7.0,-37.0,-62.0,20.0
133381,GB,United Kingdom,York,NaN,NaN,GB-YOR,NaN,ChIJh-IigLwxeUgRAKFv7Z75DAM,2020-12-31,-46.0,3.0,7.0,-57.0,-67.0,23.0

In [6]:
london = google[google.sub_region_1=='Greater London']
london

,country_region_code,country_region,sub_region_1,sub_region_2,metro_area,iso_3166_2_code,census_fips_code,place_id,date,retail_and_recreation_percent_change_from_baseline,grocery_and_pharmacy_percent_change_from_baseline,parks_percent_change_from_baseline,transit_stations_percent_change_from_baseline,workplaces_percent_change_from_baseline,residential_percent_change_from_baseline
36253,GB,United Kingdom,Greater London,NaN,NaN,NaN,NaN,ChIJb-IaoQug2EcRi-m4hONz8S8,2020-02-15,-11.0,-8.0,-34.0,-10.0,-3.0,2.0
36254,GB,United Kingdom,Greater London,NaN,NaN,NaN,NaN,ChIJb-IaoQug2EcRi-m4hONz8S8,2020-02-16,-9.0,-11.0,-41.0,-9.0,-4.0,1.0
36255,GB,United Kingdom,Greater London,NaN,NaN,NaN,NaN,ChIJb-IaoQug2EcRi-m4hONz8S8,2020-02-17,11.0,4.0,28.0,-3.0,-13.0,2.0
36256,GB,United Kingdom,Greater London,NaN,NaN,NaN,NaN,ChIJb-IaoQug2EcRi-m4hONz8S8,2020-02-18,4.0,-2.0,11.0,-4.0,-13.0,2.0
36257,GB,United Kingdom,Greater London,NaN,NaN,NaN,NaN,ChIJb-IaoQug2EcRi-m4hONz8S8,2020-02-19,3.0,-3.0,3.0,-5.0,-13.0,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
47162,GB,United Kingdom,Greater London,Royal Borough of Kingston upon Thames,NaN,GB-KTT,NaN,ChIJ0ycUEikKdkgR6r_eW1XvlAQ,2020-12-27,-72.0,-31.0,40.0,-58.0,-42.0,12.0
47163,GB,United Kingdom,Greater London,Royal Borough of Kingston upon Thames,NaN,GB-KTT,NaN,ChIJ0ycUEikKdkgR6r_eW1XvlAQ,2020-12-28,-67.0,-32.0,NaN,-76.0,-84.0,32.0
47164,GB,United Kingdom,Greater London,Royal Borough of Kingston upon Thames,NaN,GB-KTT,NaN,ChIJ0ycUEikKdkgR6r_eW1XvlAQ,2020-12-29,-62.0,-19.0,NaN,-69.0,-77.0,29.0
47165,GB,United Kingdom,Greater London,Royal Borough of Kingston upon Thames,NaN,GB-KTT,NaN,ChIJ0ycUEikKdkgR6r_eW1XvlAQ,2020-12-30,-61.0,-10.0,NaN,-68.0,-74.0,30.0
47166,GB,United Kingdom,Greater London,Royal Borough of Kingston upon Thames,NaN,GB-KTT,NaN,ChIJ0ycUEikKdkgR6r_eW1XvlAQ,2020-12-31,-63.0,-3.0,NaN,-70.0,-77.0,30.0

In [15]:
london_all = london[london.sub_region_2]
london_all

SyntaxError: invalid syntax (<ipython-input-15-ab1ec248c042>, line 1)

In [18]:
np.isnan(london.sub_region_2)

TypeError: ufunc 'isnan' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''